# Generated by Django 5.2.12 on 2026-03-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(default=999999999999999, max_length=15),
            preserve_default=False,
        ),
    ]
